<?php

namespace Inmobiliaria\Bundle\ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TemporatyRentalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemporatyRentalRepository extends EntityRepository
{
}
