parameters:
#    inmobiliaria_api.example.class: Inmobiliaria\Bundle\ApiBundle\Example

services:
#    inmobiliaria_api.example:
#        class: %inmobiliaria_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
